export const TOPICS: string[] = [
  "Day 1 ? What is Python, print, input/output",
  "Day 2 ? Variables, data types, operators",
  "Day 3 ? If-else, loops",
  "Day 4 ? Functions",
  "Day 5 ? Mini project ? calculator",
  "Day 6 ? Lists and tuples",
  "Day 7 ? Dictionaries and sets",
  "Day 8 ? Strings and loops",
  "Day 9 ? Error handling",
  "Day 10 ? Mini project ? quiz or word counter",
  "Day 11 ? NumPy basics",
  "Day 12 ? Pandas (dataframes)",
  "Day 13 ? Data filtering",
  "Day 14 ? Matplotlib visualization",
  "Day 15 ? CSV analysis mini-project",
  "Day 16 ? What is Machine Learning",
  "Day 17 ? Install Scikit-learn",
  "Day 18 ? Linear regression example",
  "Day 19 ? Decision Tree example",
  "Day 20 ? Mini project ? predict house prices",
];
